### ISSUE TITLE
Let error-class take multiple keys

### ISSUE THREAD

**Issue by sooheon** [pupeno/free-form#15]
There may be a better way to do this, but it'd be cool if `{free-form/error-class {:keys [:email :-general] :error "error"}}` worked. I may want every input field to be in error state upon a general error, for example.

**Comment by pupeno** [comment]
I don't think I have a use for this, but it wouldn't hurt, so I added some functionality to the [free-form-examples](http://free-form-examples.pupeno.com/) to be able to play with validations and then I'll implement this (unless you want to do it): https://github.com/pupeno/free-form-examples/commit/5f432330d9ab551e09fbc3ad458791d81863a981

**Comment by pupeno** [comment]
Let me know if you need a release of this.
