### ISSUE TITLE
Issue with space key

### ISSUE THREAD

**Issue by owengalenjones** [pupeno/free-form#30]
Hello I'm trying to use free-form in a re-frame app but am experiencing a weird issue with the space key.  When you press space when a field is focused the cursor will jump to the first character instead of inputting a space.  You can replicate yourself on the http://free-form-examples.pupeno.com/re-frame/bootstrap-3 demo in the email field.

**Comment by pupeno** [comment]
Yup, that's a bug. I'll look into it. Thanks for the report @owengalenjones

**Comment by pupeno** [comment]
This is actually quite odd. If you check the text field, it doesn't have that problem. A text and an email field are, for free-from, identical. The only difference is the type that allows the browser to know more about the form, do validation, etc. If you are building an SPA, you may not want that validation anyway.

Now, the interesting bit is that the bug you experienced is present in Chrome but *not* Internet Explorer. It's something about Chrome's handling of email fields.

**Comment by pupeno** [comment]
As a workaround, I'd recommend just sticking to text fields for now.

**Comment by owengalenjones** [comment]
@pupeno that's wild, I didn't even realize it was an `email` type field, I think I must've just copied from the `free-form` example.  That's very frustrating for Chrome to "help" with this.

Thanks!
